### ISSUE TITLE
Release all the packages with the same version

### ISSUE THREAD

**Issue by singuerinc** [atlassian/lerna-semantic-release#43]
Question: Is it possible to release all the packages with the same version?
Regardless the packages I change, I would like to change all the versions.

For example, I have this mono-repo structure:
```
--/
----packages
------ module-a
------ module-b
------ module-c
```

If I change something in `module-a` and the version is `0.0.1` I would like to change module-b and module-c also to `0.0.1`

**Comment by jpnelson** [comment]
Currently not – this would mean adding support for https://github.com/atlassian/lerna#fixedlocked-mode-default . I do wonder if there's much value in doing that though, since most of the features here are for the difficulties imposed by independent versioning.

Would you consider using regular semantic-release, and adding support for `lerna publish` in the place of `npm publish` there?

**Comment by jpnelson** [comment]
I'll close this one for now, but for posterity, that is my recommendation.
