### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by jpnelson** [atlassian/lerna-semantic-release#62]
I'd be happy with sticking pretty closely to the airbnb styles

**Comment by alexreardon** [comment]
My vote is to stay very close to the [AtlasKit eslint rules](https://bitbucket.org/atlassian/atlaskit/src/f6572e812b06b385ab6b83bca30b82c5ace59e3c/packages/eslint-config-base/?at=master) for easy cross repo work. Because that package is versioned this repo could just extend that.

so the `.eslintrc` in this repo would look like:
```
{
  "extends": "@atlaskit/eslint-config-base"
}
```

**Comment by vovacodes** [comment]
@alexreardon do you propose to use a closed-source `eslint` config for the open-source package? Doesn't seem right to me

**Comment by alexreardon** [comment]
My apologies, I did not realise that repo was closed source. I think it was open source at one stage but that is no longer the case. Please ignore my suggestion

**Comment by vovacodes** [comment]
I added a very simple config, please, let me know if you'd like some preferences included there
